name: Comment
on: pull_request
jobs:
  comment:                   # ジョブID（任意のIDをつけられる）
    runs-on: ubuntu-latest
    permissions:             # GITHUB _TOKENの権限を指定
      pull-requests: write   # プルリクエストの書き込みを許可
      contents: read         # ソースコードの読み込みを許可
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" --body "Hello, ${GITHUB_ACTOR}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub CLI用クレデンシャル