name: Conditions workflow
on: push
jobs:
  skip-or-run:                           # ジョブID（任意のIDをつけられる）
    if: ${{ github.actor == 'octocat' }} # octocatアカウント以外は実行をスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello"