name: GITHUB_ENV
on: push
jobs:
  share:                                             # ジョブID（任意のIDをつけられる）
    runs-on: ubuntu-latest
    steps:
      - run: echo "RESULT=hello" >> "${GITHUB_ENV}"  # GITHUB_ENVへ書き出し
      - run: echo "${RESULT}"                        # 通常の環境変数として参照